'''
This file is part of the smICA repository that is distributed under the MIT license; see below.
This script is usefull when the ROI is created with imageJ as a text image. The scrit allows to convert the files generated by ImageJ into the format readable by the smICA software.

############################################################################

MIT License

Copyright (c) 2026 Tomasz Kalwarczyk

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
'''
with open('../LICENSE', 'r') as file:
    Licence = file.read()
with open('../VERSION', 'r') as file:
    VERSION = file.read()

global _path
line='=============================================================================='
def execfile(filepath, globals=globals(), locals=None):
    '''Import module allowing execution of external python scripts as part of the main code. This part of the code is based on the following source: https://stackoverflow.com/a/41658338 '''
    globals.update({
        "__file__": filepath,
        "__name__": "__main__",
    })
    with open(filepath, 'rb') as file:
        exec(compile(file.read(), filepath, 'exec'), globals, locals)

import sys
_Arguments = len(sys.argv) - 1
import dearpygui.dearpygui as dpg
import os
import pandas as pd
import numpy as np

print(line)
print(line,end='\n\n')
print(Licence)
print('\n')
print('VERSION = ',VERSION,end='\n')
print(line)
print(line,end='\n\n')


_path = ''
execfile(os.path.join('dep','Functions.py'))          

dpg.create_context()                        

execfile(os.path.join('dep','init.py'))               

execfile(os.path.join('dep','Themes.py'))             

execfile(os.path.join('dep','Fonts.py'))              

dpg.create_viewport(title='Rewrite roi GUI' ,
                    width=800,
                    height=400,
                    x_pos=0,
                    y_pos  =0,
                    resizable=True)    

execfile(os.path.join('dep','Menu_bar_functions.py')) 

execfile(os.path.join('dep','Menu_bar.py'))           

dpg.setup_dearpygui()
    
dpg.show_viewport(maximized=False)    

with dpg.window(label='',
                pos = (init_left_indent,init_top_indent),
                no_move=False,
                no_close=True,
                no_title_bar=True,
                no_resize=True,
                tag='file_window',
                autosize=True,
                show=True
               ):
    dpg.add_button(label='Open ROI folder',
                   tag='open_roi_folder',
                   width=600,
                   callback=lambda: dpg.show_item('Source_file_dialog')
                  )
    dpg.add_text('',tag='tag_source_path',wrap=600)
    with dpg.group(tag='resolution_group', horizontal=True):
        dpg.add_input_text(tag='add_text_width',width=288)
        dpg.add_text('x',tag='tag_x')
        dpg.add_input_text(tag='add_text_height',width=289)
    dpg.add_button(label='Target ROI folder',
                   tag='target_roi_folder',
                   width=600,
                   callback=lambda: dpg.show_item('Target_file_dialog')
                  )
    dpg.add_text('',tag='tag_target_path',wrap=600)
   
    dpg.add_listbox(items=[],
                    width=600,
                    tag='file_box'
                   )
    
    dpg.add_button(label='Proceded',tag='Run_script',width=600,callback=callback_proceed)


execfile(os.path.join('dep','Dialogs.py'))                     


if _Arguments:
    print(f"Script started with {_Arguments} argument(s): {sys.argv[1:]}")
    source_path = {'file_path_name':sys.argv[1]}
    
    resolution = sys.argv[2]
    
    resolution = resolution.split('x')
    
    target_path = {'file_path_name':sys.argv[3]}
    
    callback_open_source_folder('Source_file_dialog',source_path)
    
    dpg.set_value('add_text_width',resolution[0])
    
    dpg.set_value('add_text_height',resolution[1])
    
    callback_open_target_folder('Target_file_dialog',target_path)
    
    callback_proceed('Run_script',None)
    
    dpg.stop_dearpygui()
    
    dpg.destroy_context
    
else:
    pass

dpg.start_dearpygui()

dpg.destroy_context
